#!/bin/sh

# Set these paths appropriately

BIN="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/bin"
CMD="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/cmd"
LIB="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/swahili-abbreviations
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
