#!/bin/sh

# Set these paths appropriately

BIN="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/bin"
CMD="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/cmd"
LIB="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

