#!/bin/sh

# Set these paths appropriately

BIN="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/bin"
CMD="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/cmd"
LIB="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/estonian-abbreviations
PARFILE=${LIB}/estonian.par
MWLFILE=${LIB}/estonian-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

