#!/bin/sh

# Set these paths appropriately

BIN="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/bin"
CMD="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/cmd"
LIB="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/spanish-abbreviations
PARFILE=${LIB}/spanish-ancora.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
