#!/bin/sh

# Set these paths appropriately

BIN="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/bin"
CMD="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/cmd"
LIB="/Users/zhengsongyi/Desktop/2022Spring/Capstone/test/Applications/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
